import {
  ConfidenceLevel,
  EmbeddingState,
  FreshnessState,
  KnowledgeEdgeKind,
  KnowledgeNodeKind,
  type GraphSnapshot,
} from "@agent-knowledge-hub/core";

const now = "2026-06-04T00:00:00.000Z";

export const GENERIC_AGENT_KNOWLEDGE_HUB_DEMO_GRAPH: GraphSnapshot = {
  sources: [
    {
      id: "source:profile-md",
      type: "markdown",
      label: "Profile knowledge file",
      uri: "file://.agent/profile.md",
      capturedAt: now,
    },
    {
      id: "source:portfolio-json",
      type: "json",
      label: "Portfolio registry",
      uri: "file://config/portfolio.json",
      capturedAt: now,
    },
    {
      id: "source:people-index",
      type: "markdown",
      label: "People index",
      uri: "file://.agent/people/index.md",
      capturedAt: now,
    },
    {
      id: "source:interaction-log",
      type: "markdown",
      label: "Interaction note",
      uri: "file://.agent/people/example-interactions.md",
      capturedAt: now,
    },
    {
      id: "source:frameworks",
      type: "markdown",
      label: "Framework library",
      uri: "file://.agent/knowledge/frameworks.md",
      capturedAt: now,
    },
  ],
  nodes: [
    {
      id: "entity:owner",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Example AI Engineer",
      body: "Full-stack AI engineer building agent workflows, retrieval systems, and productized automation.",
      tags: ["about-me", "profile", "identity"],
      metadata: { entityType: "person", visibility: "private-demo" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "knowledge:headline",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Professional headline",
      body: "AI product engineer focused on Next.js, TypeScript, workflow automation, semantic retrieval, and graph-backed agent memory.",
      tags: ["about-me", "profile", "portfolio"],
      metadata: { field: "headline" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:application-defaults",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Application defaults",
      body: "Use immediate availability, remote-friendly preference, AI engineering positioning, and concise evidence-backed answers for job applications.",
      tags: ["corporate", "application-answer", "about-me"],
      metadata: { answerType: "job-application-default" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:service-offer-agent-os",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Service offer: agent operating systems",
      body: "Design and implement agent operating systems with workflow orchestration, durable memory, retrieval, dashboards, and automation control loops.",
      tags: ["freelance", "service", "agent-os"],
      metadata: { offerType: "service" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:service-offer-retrieval",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Service offer: retrieval systems",
      body: "Build RAG and graph retrieval systems with source-backed answers, freshness tracking, dedupe, and agent-accessible context APIs.",
      tags: ["freelance", "service", "retrieval"],
      metadata: { offerType: "service" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:portfolio-operations-console",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Portfolio project: Operations Console",
      body: "An internal operations console coordinating knowledge, agents, leads, content, and dashboards. Workflow definitions and run logs are not knowledge records.",
      tags: ["portfolio", "product", "internal-console"],
      metadata: { projectType: "internal-product" },
      sourceIds: ["source:portfolio-json"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:framework-source-backed-answer",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Framework: source-backed answer",
      body: "Every agent answer should separate facts from inference, cite source nodes when available, and mark stale or low-confidence claims before use.",
      tags: ["framework", "agent-quality", "anti-hallucination"],
      metadata: { frameworkType: "retrieval" },
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:framework-outreach-fit",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Framework: outreach fit scoring",
      body: "Prioritize leads by role relevance, company AI maturity, public hiring signals, warm connection paths, and clear service fit.",
      tags: ["framework", "sales", "outreach"],
      metadata: { frameworkType: "lead-scoring" },
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:highlevel",
      kind: KnowledgeNodeKind.ENTITY,
      label: "HighLevel",
      body: "CRM and marketing automation company used as a sample target company entity.",
      tags: ["company", "target-account", "crm"],
      metadata: { entityType: "company", domain: "gohighlevel.com" },
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.NEEDS_REVIEW,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:acme-ai",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Acme AI Studio",
      body: "Synthetic AI automation agency account for validating company relationship graphs.",
      tags: ["company", "target-account", "agency"],
      metadata: { entityType: "company", domain: "example.ai" },
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:virendra-sharma",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Virendra Sharma",
      body: "Synthetic contact persona representing a hiring or partnership lead.",
      tags: ["person", "lead", "linkedin"],
      metadata: { entityType: "person", role: "Engineering Leader" },
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.NEEDS_REVIEW,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:maya-patel",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Maya Patel",
      body: "Synthetic founder persona interested in automating sales and delivery workflows.",
      tags: ["person", "lead", "wellfound"],
      metadata: { entityType: "person", role: "Founder" },
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "interaction:linkedin-dm-virendra",
      kind: KnowledgeNodeKind.INTERACTION,
      label: "LinkedIn DM to Virendra",
      body: "Sent a concise message referencing AI workflow automation, retrieval quality, and a possible engineering fit.",
      tags: ["interaction", "linkedin", "outreach"],
      metadata: { channel: "linkedin", direction: "outbound", status: "sent" },
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "interaction:wellfound-maya",
      kind: KnowledgeNodeKind.INTERACTION,
      label: "Wellfound note for Maya",
      body: "Prepared a pitch around building an internal agent OS for agency delivery and lead operations.",
      tags: ["interaction", "wellfound", "outreach"],
      metadata: { channel: "wellfound", direction: "outbound", status: "drafted" },
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.PENDING,
    },
    {
      id: "source-node:profile-md",
      kind: KnowledgeNodeKind.SOURCE,
      label: "Source: profile.md",
      body: "Synthetic source node representing an imported profile markdown file.",
      tags: ["source", "markdown", "profile"],
      metadata: { sourceRef: "source:profile-md" },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.NOT_INDEXED,
    },
    {
      id: "source-node:people-index",
      kind: KnowledgeNodeKind.SOURCE,
      label: "Source: people index",
      body: "Synthetic source node representing the people and interaction index.",
      tags: ["source", "markdown", "people"],
      metadata: { sourceRef: "source:people-index" },
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.NOT_INDEXED,
    },
    {
      id: "chunk:application-defaults:0",
      kind: KnowledgeNodeKind.CHUNK,
      label: "Chunk: application defaults",
      body: "Immediate availability, remote-friendly preference, AI engineering positioning, and concise evidence-backed answers.",
      tags: ["chunk", "corporate", "application-answer"],
      metadata: { parentNodeId: "knowledge:application-defaults", chunkOrder: 0 },
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "chunk:source-backed-answer:0",
      kind: KnowledgeNodeKind.CHUNK,
      label: "Chunk: source-backed answer",
      body: "Separate facts from inference, cite source nodes, and mark stale or low-confidence claims.",
      tags: ["chunk", "framework", "agent-quality"],
      metadata: { parentNodeId: "knowledge:framework-source-backed-answer", chunkOrder: 0 },
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
  ],
  edges: [
    {
      id: "edge:owner-headline",
      fromId: "entity:owner",
      toId: "knowledge:headline",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "has headline",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:owner-defaults",
      fromId: "entity:owner",
      toId: "knowledge:application-defaults",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "uses answer defaults",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:owner-agent-os",
      fromId: "entity:owner",
      toId: "knowledge:service-offer-agent-os",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "offers",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:owner-retrieval",
      fromId: "entity:owner",
      toId: "knowledge:service-offer-retrieval",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "offers",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:career-os-uses-framework",
      fromId: "knowledge:portfolio-career-os",
      toId: "knowledge:framework-source-backed-answer",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "uses quality rule",
      metadata: {},
      sourceIds: ["source:portfolio-json", "source:frameworks"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:virendra-works-at-highlevel",
      fromId: "entity:virendra-sharma",
      toId: "entity:highlevel",
      kind: KnowledgeEdgeKind.WORKS_AT,
      label: "works at",
      metadata: {},
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:maya-works-at-acme",
      fromId: "entity:maya-patel",
      toId: "entity:acme-ai",
      kind: KnowledgeEdgeKind.WORKS_AT,
      label: "founded",
      metadata: {},
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:dm-sent-to-virendra",
      fromId: "interaction:linkedin-dm-virendra",
      toId: "entity:virendra-sharma",
      kind: KnowledgeEdgeKind.SENT_MESSAGE_TO,
      label: "sent message to",
      metadata: { channel: "linkedin" },
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:wellfound-contacted-maya",
      fromId: "interaction:wellfound-maya",
      toId: "entity:maya-patel",
      kind: KnowledgeEdgeKind.CONTACTED,
      label: "contacted",
      metadata: { channel: "wellfound" },
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:dm-supports-retrieval-offer",
      fromId: "interaction:linkedin-dm-virendra",
      toId: "knowledge:service-offer-retrieval",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "mentions offer",
      metadata: {},
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:wellfound-supports-agent-os",
      fromId: "interaction:wellfound-maya",
      toId: "knowledge:service-offer-agent-os",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "mentions offer",
      metadata: {},
      sourceIds: ["source:interaction-log"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:outreach-fit-to-highlevel",
      fromId: "knowledge:framework-outreach-fit",
      toId: "entity:highlevel",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "scores account",
      metadata: {},
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.INFERRED,
    },
    {
      id: "edge:outreach-fit-to-acme",
      fromId: "knowledge:framework-outreach-fit",
      toId: "entity:acme-ai",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "scores account",
      metadata: {},
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.INFERRED,
    },
    {
      id: "edge:profile-derived-headline",
      fromId: "knowledge:headline",
      toId: "source-node:profile-md",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:defaults-derived-from-profile",
      fromId: "knowledge:application-defaults",
      toId: "source-node:profile-md",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:people-derived-from-index",
      fromId: "entity:virendra-sharma",
      toId: "source-node:people-index",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:people-index"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:chunk-belongs-defaults",
      fromId: "chunk:application-defaults:0",
      toId: "knowledge:application-defaults",
      kind: KnowledgeEdgeKind.BELONGS_TO,
      label: "chunk of",
      metadata: {},
      sourceIds: ["source:profile-md"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:chunk-belongs-framework",
      fromId: "chunk:source-backed-answer:0",
      toId: "knowledge:framework-source-backed-answer",
      kind: KnowledgeEdgeKind.BELONGS_TO,
      label: "chunk of",
      metadata: {},
      sourceIds: ["source:frameworks"],
      confidence: ConfidenceLevel.IMPORTED,
    },
  ],
};

export const ENTITY_GRAPH_DEMO_NODE_IDS = GENERIC_AGENT_KNOWLEDGE_HUB_DEMO_GRAPH.nodes
  .filter((node) => node.kind === KnowledgeNodeKind.ENTITY || node.kind === KnowledgeNodeKind.INTERACTION)
  .map((node) => node.id);
