import {
  ConfidenceLevel,
  EmbeddingState,
  FreshnessState,
  KnowledgeEdgeKind,
  KnowledgeNodeKind,
  type GraphSnapshot,
} from "@agent-knowledge-hub/core";

const now = "2026-06-04T00:00:00.000Z";

export const GENERIC_AGENT_KNOWLEDGE_HUB_DEMO_GRAPH: GraphSnapshot = {
  sources: [
    {
      id: "source:product-catalog",
      type: "markdown",
      label: "Product catalog",
      uri: "file://knowledge/products/catalog.md",
      capturedAt: now,
    },
    {
      id: "source:team-handbook",
      type: "markdown",
      label: "Team handbook",
      uri: "file://knowledge/teams/handbook.md",
      capturedAt: now,
    },
    {
      id: "source:customer-notes",
      type: "json",
      label: "Customer notes export",
      uri: "file://imports/customers/notes.json",
      capturedAt: now,
    },
    {
      id: "source:support-activity",
      type: "markdown",
      label: "Support activity log",
      uri: "file://activity/support/may.md",
      capturedAt: now,
    },
    {
      id: "source:reference-library",
      type: "markdown",
      label: "Reference library",
      uri: "file://knowledge/reference/retrieval.md",
      capturedAt: now,
    },
  ],
  nodes: [
    {
      id: "entity:atlas-cloud",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Atlas Cloud",
      body: "Sample software platform that centralizes product knowledge, customer activity, and source-backed agent retrieval.",
      tags: ["company", "platform"],
      metadata: { entityType: "organization", visibility: "demo" },
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "entity:platform-team",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Platform Team",
      body: "Team responsible for ingestion, retrieval quality, and graph consistency across knowledge services.",
      tags: ["team", "engineering"],
      metadata: { entityType: "team" },
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:solstice-retail",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Solstice Retail",
      body: "Sample customer account used to validate entity relationships and service activity flows.",
      tags: ["customer", "retail"],
      metadata: { entityType: "company", domain: "solstice.example" },
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "entity:maya-chen",
      kind: KnowledgeNodeKind.ENTITY,
      label: "Maya Chen",
      body: "Synthetic customer operations lead who coordinates rollout status and support follow-ups.",
      tags: ["person", "customer-contact"],
      metadata: { entityType: "person", role: "Operations Lead" },
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:platform-summary",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Platform summary",
      body: "Atlas Cloud combines graph storage, vector search, and source references to support agent answers with traceable context.",
      tags: ["product", "summary"],
      metadata: { field: "overview" },
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:ingestion-policy",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Ingestion policy",
      body: "Ingest durable product records, customer facts, and support notes while leaving transient job state in the application database.",
      tags: ["policy", "ingestion"],
      metadata: { policyType: "ingestion" },
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:retrieval-guideline",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Retrieval guideline",
      body: "Agent answers should separate facts from inference, cite source-backed records, and surface stale or low-confidence results clearly.",
      tags: ["framework", "retrieval"],
      metadata: { frameworkType: "quality" },
      sourceIds: ["source:reference-library"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:customer-rollout",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Customer rollout note",
      body: "Solstice Retail is piloting knowledge-backed support operations for its team with weekly review checkpoints.",
      tags: ["customer", "rollout"],
      metadata: { recordType: "rollout-note" },
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.NEEDS_REVIEW,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:service-playbook",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Service playbook",
      body: "Support teams resolve incidents faster when customer context, product references, and prior actions are linked in one graph-backed workspace.",
      tags: ["service", "playbook"],
      metadata: { recordType: "playbook" },
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "interaction:support-review",
      kind: KnowledgeNodeKind.INTERACTION,
      label: "Support review meeting",
      body: "Review meeting covering rollout status, open issues, and knowledge coverage gaps for the Solstice account.",
      tags: ["interaction", "meeting"],
      metadata: { channel: "meeting", status: "completed" },
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "interaction:follow-up-email",
      kind: KnowledgeNodeKind.INTERACTION,
      label: "Follow-up email",
      body: "Shared source-backed references for onboarding and clarified which data remains operational instead of knowledge-backed.",
      tags: ["interaction", "email"],
      metadata: { channel: "email", status: "sent" },
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.PENDING,
    },
    {
      id: "source-node:product-catalog",
      kind: KnowledgeNodeKind.SOURCE,
      label: "Source: product catalog",
      body: "Synthetic source node representing an imported product catalog.",
      tags: ["source", "catalog"],
      metadata: { sourceRef: "source:product-catalog" },
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.NOT_INDEXED,
    },
    {
      id: "source-node:customer-notes",
      kind: KnowledgeNodeKind.SOURCE,
      label: "Source: customer notes",
      body: "Synthetic source node representing imported customer notes and rollout records.",
      tags: ["source", "customer"],
      metadata: { sourceRef: "source:customer-notes" },
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.NOT_INDEXED,
    },
    {
      id: "chunk:platform-summary:0",
      kind: KnowledgeNodeKind.CHUNK,
      label: "Chunk: platform summary",
      body: "Graph storage, vector search, and source references support traceable agent answers.",
      tags: ["chunk", "product"],
      metadata: { parentNodeId: "knowledge:platform-summary", chunkOrder: 0 },
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "chunk:ingestion-policy:0",
      kind: KnowledgeNodeKind.CHUNK,
      label: "Chunk: ingestion policy",
      body: "Keep durable facts in the knowledge layer and leave transient job state in the application database.",
      tags: ["chunk", "policy"],
      metadata: { parentNodeId: "knowledge:ingestion-policy", chunkOrder: 0 },
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "chunk:retrieval-guideline:0",
      kind: KnowledgeNodeKind.CHUNK,
      label: "Chunk: retrieval guideline",
      body: "Separate facts from inference and show source-backed evidence with confidence signals.",
      tags: ["chunk", "retrieval"],
      metadata: { parentNodeId: "knowledge:retrieval-guideline", chunkOrder: 0 },
      sourceIds: ["source:reference-library"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:integration-checklist",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Integration checklist",
      body: "Verify source imports, graph relationships, vector dimensions, and retrieval smoke tests before enabling agent access.",
      tags: ["checklist", "integration"],
      metadata: { recordType: "checklist" },
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
      freshness: FreshnessState.FRESH,
      embeddingState: EmbeddingState.INDEXED,
    },
    {
      id: "knowledge:incident-summary",
      kind: KnowledgeNodeKind.KNOWLEDGE_ITEM,
      label: "Incident summary",
      body: "A recent support issue was resolved by linking customer configuration notes to product references and prior investigation steps.",
      tags: ["incident", "support"],
      metadata: { recordType: "incident-summary" },
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.IMPORTED,
      freshness: FreshnessState.NEEDS_REVIEW,
      embeddingState: EmbeddingState.INDEXED,
    },
  ],
  edges: [
    {
      id: "edge:atlas-summary",
      fromId: "entity:atlas-cloud",
      toId: "knowledge:platform-summary",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "described by",
      metadata: {},
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:platform-team-policy",
      fromId: "entity:platform-team",
      toId: "knowledge:ingestion-policy",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "maintains",
      metadata: {},
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:platform-team-playbook",
      fromId: "entity:platform-team",
      toId: "knowledge:service-playbook",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "maintains",
      metadata: {},
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:platform-team-checklist",
      fromId: "entity:platform-team",
      toId: "knowledge:integration-checklist",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "uses",
      metadata: {},
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.USER_CONFIRMED,
    },
    {
      id: "edge:retrieval-guideline-atlas",
      fromId: "knowledge:retrieval-guideline",
      toId: "entity:atlas-cloud",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "applies to",
      metadata: {},
      sourceIds: ["source:reference-library", "source:product-catalog"],
      confidence: ConfidenceLevel.INFERRED,
    },
    {
      id: "edge:maya-works-at-solstice",
      fromId: "entity:maya-chen",
      toId: "entity:solstice-retail",
      kind: KnowledgeEdgeKind.WORKS_AT,
      label: "works at",
      metadata: {},
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:support-review-customer",
      fromId: "interaction:support-review",
      toId: "entity:solstice-retail",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "reviews account",
      metadata: { channel: "meeting" },
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:follow-up-email-contact",
      fromId: "interaction:follow-up-email",
      toId: "entity:maya-chen",
      kind: KnowledgeEdgeKind.SENT_MESSAGE_TO,
      label: "sent to",
      metadata: { channel: "email" },
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:support-review-rollout",
      fromId: "interaction:support-review",
      toId: "knowledge:customer-rollout",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "updates",
      metadata: {},
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:follow-up-email-incident",
      fromId: "interaction:follow-up-email",
      toId: "knowledge:incident-summary",
      kind: KnowledgeEdgeKind.SUPPORTS,
      label: "references",
      metadata: {},
      sourceIds: ["source:support-activity"],
      confidence: ConfidenceLevel.OBSERVED,
    },
    {
      id: "edge:customer-rollout-solstice",
      fromId: "knowledge:customer-rollout",
      toId: "entity:solstice-retail",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "describes",
      metadata: {},
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:platform-summary-derived",
      fromId: "knowledge:platform-summary",
      toId: "source-node:product-catalog",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:customer-rollout-derived",
      fromId: "knowledge:customer-rollout",
      toId: "source-node:customer-notes",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:maya-derived",
      fromId: "entity:maya-chen",
      toId: "source-node:customer-notes",
      kind: KnowledgeEdgeKind.DERIVED_FROM,
      label: "derived from",
      metadata: {},
      sourceIds: ["source:customer-notes"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:chunk-platform-summary",
      fromId: "chunk:platform-summary:0",
      toId: "knowledge:platform-summary",
      kind: KnowledgeEdgeKind.BELONGS_TO,
      label: "chunk of",
      metadata: {},
      sourceIds: ["source:product-catalog"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:chunk-ingestion-policy",
      fromId: "chunk:ingestion-policy:0",
      toId: "knowledge:ingestion-policy",
      kind: KnowledgeEdgeKind.BELONGS_TO,
      label: "chunk of",
      metadata: {},
      sourceIds: ["source:team-handbook"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:chunk-retrieval-guideline",
      fromId: "chunk:retrieval-guideline:0",
      toId: "knowledge:retrieval-guideline",
      kind: KnowledgeEdgeKind.BELONGS_TO,
      label: "chunk of",
      metadata: {},
      sourceIds: ["source:reference-library"],
      confidence: ConfidenceLevel.IMPORTED,
    },
    {
      id: "edge:incident-playbook",
      fromId: "knowledge:incident-summary",
      toId: "knowledge:service-playbook",
      kind: KnowledgeEdgeKind.RELATED_TO,
      label: "informed by",
      metadata: {},
      sourceIds: ["source:support-activity", "source:team-handbook"],
      confidence: ConfidenceLevel.INFERRED,
    },
  ],
};

export const ENTITY_GRAPH_DEMO_NODE_IDS = GENERIC_AGENT_KNOWLEDGE_HUB_DEMO_GRAPH.nodes
  .filter((node) => node.kind === KnowledgeNodeKind.ENTITY || node.kind === KnowledgeNodeKind.INTERACTION)
  .map((node) => node.id);
